package br.com.barcadero.module.sat.enums;

public enum EnumCFeTipoFuncao {
	
	CFE_ASSOCIAR_ASSINATURA,
	CFE_ATIVA_SAT,
	CFE_ATUALIZAR_SOFTWARE_SAT,
	CFE_BLOQUEAR_SAT,
	CFE_CANCELAR_ULTIMA_VENDA,
	CFE_CONSULTAR_NUMERO_SESSAO,
	CFE_CONSULTAR_SAT,
	CFE_CONSULTAR_STATUS_OPERACIONAL,
	CFE_DESBLOQUEAR_SAT,
	CFE_ENVIAR_DADOS_VENDA,
	CFE_EXTRAIR_LOGS,
	CFE_TESTE_FIM_A_FIM,
	CFE_TROCAR_CODIGO_DE_ATIVACAO
}
